package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode/utf8"
)

const adapterVersion = "0.2.0"

var genericLanguagePattern = regexp.MustCompile(`^generic-([a-z0-9]+)$`)

var supportedExtensions = map[string]struct{}{
	"asm": {}, "bash": {}, "bat": {}, "c": {}, "cc": {}, "clj": {}, "cljs": {}, "cmd": {},
	"cpp": {}, "cr": {}, "cs": {}, "dart": {}, "elm": {}, "erl": {}, "ex": {}, "exs": {},
	"f03": {}, "f90": {}, "f95": {}, "fish": {}, "fs": {}, "fsx": {}, "groovy": {}, "h": {},
	"hh": {}, "hpp": {}, "hs": {}, "java": {}, "jl": {}, "kt": {}, "kts": {}, "lhs": {},
	"lua": {}, "m": {}, "ml": {}, "mli": {}, "mm": {}, "nim": {}, "nims": {}, "pas": {},
	"php": {}, "pl": {}, "pm": {}, "proto": {}, "ps1": {}, "r": {}, "s": {}, "sc": {},
	"scala": {}, "sh": {}, "sol": {}, "sql": {}, "sv": {}, "swift": {}, "v": {}, "vb": {},
	"vbs": {}, "vim": {}, "zig": {},
}

func analyzeRepository(repository, language string, changedFiles, removedFiles []string, incremental bool) ([]byte, error) {
	extension, err := languageExtension(language)
	if err != nil {
		return nil, err
	}
	root, err := filepath.Abs(repository)
	if err != nil {
		return nil, fmt.Errorf("resolve repository: %w", err)
	}
	info, err := os.Stat(root)
	if err != nil {
		return nil, fmt.Errorf("stat repository: %w", err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("repository path is not a directory")
	}
	paths, err := collectSources(root, extension, changedFiles, incremental)
	if err != nil {
		return nil, err
	}
	facts := newFactSet(language)
	for _, path := range paths {
		content, readErr := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
		if readErr != nil {
			return nil, fmt.Errorf("read %s: %w", path, readErr)
		}
		if !sourceText(content) || generatedSource(content) {
			continue
		}
		moduleID := facts.addFile(path, content)
		parseSource(facts, path, moduleID, string(content))
	}
	repositoryName := filepath.Base(filepath.Clean(root))
	return facts.render(repositoryName, changedFiles, removedFiles, incremental), nil
}

func languageExtension(language string) (string, error) {
	match := genericLanguagePattern.FindStringSubmatch(strings.ToLower(language))
	if match == nil {
		return "", fmt.Errorf("invalid generic language %q", language)
	}
	if _, ok := supportedExtensions[match[1]]; !ok {
		return "", fmt.Errorf("unsupported generic source extension %q", match[1])
	}
	return "." + match[1], nil
}

func sourceText(content []byte) bool {
	return utf8.Valid(content) && !bytes.ContainsRune(content, '\x00')
}

func generatedSource(content []byte) bool {
	if len(content) > 4096 {
		content = content[:4096]
	}
	text := strings.ToLower(string(content))
	for _, marker := range []string{"code generated", "do not edit", "@generated", "<auto-generated", "auto-generated file"} {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}
