package index

import (
	"bytes"
	"io/fs"
	"path/filepath"
	"strings"
)

const minifiedContentThreshold = 16 << 10

func generatedDirectory(entry fs.DirEntry) bool {
	if !entry.IsDir() {
		return false
	}
	switch strings.ToLower(entry.Name()) {
	case "node_modules", "vendor", "third_party", "third-party", ".next", ".nuxt", "coverage", "dist", "target", "out":
		return true
	default:
		return false
	}
}

func generatedFileName(name string) bool {
	lower := strings.ToLower(name)
	switch lower {
	case "package-lock.json", "npm-shrinkwrap.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb",
		"composer.lock", "poetry.lock", "pipfile.lock", "cargo.lock", "gemfile.lock":
		return true
	}
	for _, suffix := range []string{
		".min.js", ".min.css", ".bundle.js", ".bundle.css",
		".generated.go", "_generated.go", ".generated.js", ".generated.ts",
		".gen.go", ".gen.js", ".gen.ts", ".pb.go", "_pb2.py", ".g.cs",
	} {
		if strings.HasSuffix(lower, suffix) {
			return true
		}
	}
	return false
}

func generatedFileContent(name string, content []byte) bool {
	lowerName := strings.ToLower(name)
	if !strings.HasSuffix(lowerName, ".md") && !strings.HasSuffix(lowerName, ".txt") {
		prefix := content
		if len(prefix) > 8<<10 {
			prefix = prefix[:8<<10]
		}
		lower := strings.ToLower(string(prefix))
		if strings.Contains(lower, "@generated") ||
			(strings.Contains(lower, "code generated") && strings.Contains(lower, "do not edit")) ||
			(strings.Contains(lower, "automatically generated") && strings.Contains(lower, "do not edit")) ||
			strings.Contains(lower, "this file was generated") ||
			strings.Contains(lower, "this file is generated") ||
			(strings.Contains(lower, "generated by") && strings.Contains(lower, "do not edit")) {
			return true
		}
	}
	return minifiedWebContent(lowerName, content)
}

func minifiedWebContent(name string, content []byte) bool {
	switch strings.ToLower(filepath.Ext(name)) {
	case ".js", ".jsx", ".ts", ".tsx", ".css", ".scss", ".html", ".json", ".xml":
	default:
		return false
	}
	if len(content) < minifiedContentThreshold {
		return false
	}
	lines := bytes.Split(content, []byte{'\n'})
	if len(lines) <= 4 {
		return true
	}
	longest := 0
	for _, line := range lines {
		if len(line) > longest {
			longest = len(line)
		}
	}
	return longest >= 32<<10
}
